### ISSUE TITLE
Conversion Error (Shifted Images)

### ISSUE THREAD

**Issue by jrddunbr** [kakwa/libvisio2svg#21]
Hi,

When converting some VSS stencils for a project I'm working on, most of the stencils come out fine. 
Sometimes, they don't come out fine, and are shifted down by about half of the height of the image.

A particular example I have found, from here: https://www.juniper.net/assets/visio-icons/juniper-mx-series-icons.zip

If you extract the zip, and then convert the file, the `10x10GE_MIC.svg` file will be incorrectly positioned, with the beginning of the top of the image halfway down the image "space". If I open it in ImageMagic, I can shift it to fit correctly into the viewport, but for the number of conversions I want to do, it's not practical to fix the SVG's individually.

I am entering the following to convert the vss file to svg's:

```bash
mkdir outputFolder
vss2svg-conv -i input.vss -o outputFolder
```

If you could find a fix, that would be super wonderful.

Thanks!

PS. Nice tool/library by the way, it is really helpful. I can't find anything else like it.

**Comment by kakwa** [comment]
Hello,

Thank you for your bug report.

it looks a lot like this other issue:

https://github.com/kakwa/libvisio2svg/issues/15

Unfortunately, I'm not sure I could fix it.

This tool is mainly glue code between a few libraries (libvisio, libemf2svg and libwmf). I only control libemf2svg.

It's most likely a bug in libvisio, I've already posted a bug report there:

https://bugs.documentfoundation.org/show_bug.cgi?id=106344

Unfortunately, this bug is in limbo for more than a year now.

I will check however if it's indeed coming from libvisio.

**Comment by jrddunbr** [comment]
Cool, thanks a bunch!

**Comment by kakwa** [comment]
Sorry for the long delay, this is indeed liked to https://github.com/kakwa/libvisio2svg/issues/15

The issue at play here is already mentioned in: https://bugs.documentfoundation.org/show_bug.cgi?id=106344

Closing this ticket as a duplicate.
